# Generated by Django 6.1.1 on 2026-09-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_item_member_item_created_by_itemshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='claim_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
