# Generated by Django 6.1.1 on 2026-09-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_membership_claim_code_membership_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
